### ISSUE TITLE
publish on open-vsx.org

### ISSUE THREAD

**Issue by flypenguin** [yo1dog/vscode-cursor-align#10]
can you please, please, please publish this on open-vsx.org? as simple as it is, this is one of my _most_ used extensions, and i switched to vscodium recently so it is no longer available for me. i'd be forever grateful :)

**Comment by yo1dog** [comment]
Don't think I want to maintain this in two places.

Should be trivial to download this repo and build the vsix yourself. Then you can install locally.

```sh
gh repo clone yo1dog/vscode-cursor-align
cd vscode-cursor-align
npx vsce package
```
