### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by Chiliyago** [yo1dog/vscode-cursor-align#3]
Would you mind adding some more details on how to use this tool? It looks promising but I'm not getting the Gif's. What keys are you using to do the selections and how to you execute your command to perform the spacing?  Thanks for any help you can provide.

**Comment by desrod** [comment]
I think I've sorted out how it works: 

Put your cursor at the beginning of the line you want to align, and use Shift+ctrl+down arrow to vertically select the rows you want to align. 

Don't let go of shift or ctrl, but then use the right arrow to advance the selection from the left column to the end of the next boundary. From there, use Alt+A to align. 

If you want to align based on the next value to the right, just hit the right arrow again to select more of your rows, then Alt+A to align. 

Hope that helps!

**Comment by yo1dog** [comment]
It doesn’t matter what method you use to place your cursors. To learn how to use multi-cursor and column selection see: https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor
